/**
 * Vue 3 component prop contracts — WebUI pixel-level replication of AnotherViewer
 * Android custom controls.
 *
 * FROZEN CONTRACT (Wave 0, task CA4). Component authors (F2–F7, S1–S7) implement
 * against these interfaces with `defineProps<T>()` / `defineEmits<T>()` /
 * `defineSlots<T>()`. Do NOT edit this file without the lead's approval —
 * changes must be broadcast to every downstream agent.
 *
 * Design authority: `docs/webui-roadmap.md` §UI 复刻规范. Every JSDoc cites the
 * Android control being replicated; exact colors/dimens come from
 * `app/src/main/res/values/*.xml` and the control sources under
 * `app/src/main/java/com/hippo/`.
 *
 * Domain types (GalleryInfo, DownloadInfo, …) live in `./index.ts` and are
 * imported/re-exported here — never duplicated.
 */

import type { GalleryInfo } from './index'

export type { GalleryInfo } from './index'

/* -------------------------------------------------------------------------- */
/* Theme                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * The three app themes, matching Android `Settings.THEME_*` semantics.
 * - `light`  — windowBackground #ffffff, surface #f5f5f5
 * - `dark`   — windowBackground #323232, surface #3a3a3a
 * - `black`  — AMOLED, windowBackground #000000, surface #191919
 */
export type AppTheme = 'light' | 'dark' | 'black'

/* -------------------------------------------------------------------------- */
/* Category contract                                                          */
/* -------------------------------------------------------------------------- */

/**
 * The 10 gallery categories, as string keys.
 *
 * NOTE: `GalleryInfo.category` (see `./index.ts`) is a NUMBER carrying the
 * Android `SiteConfig` bit value (see {@link CATEGORY_BIT_VALUES}); components
 * render via this string union. Convert with {@link CATEGORY_BY_BIT}.
 */
export type GalleryCategory =
  | 'doujinshi'
  | 'manga'
  | 'artist_cg'
  | 'game_cg'
  | 'western'
  | 'non_h'
  | 'image_set'
  | 'cosplay'
  | 'asian_porn'
  | 'misc'

/**
 * Display order of {@link GalleryCategory} in `CategoryTable`
 * (Android `widget_category_table.xml`: 2 columns × 5 rows, row-major).
 */
export const CATEGORY_ORDER: readonly GalleryCategory[] = [
  'doujinshi',
  'manga',
  'artist_cg',
  'game_cg',
  'western',
  'non_h',
  'image_set',
  'cosplay',
  'asian_porn',
  'misc',
] as const

/** Human-readable labels (Android `SiteUtils.getCategory(int)` strings). */
export const CATEGORY_LABELS: Readonly<Record<GalleryCategory, string>> = {
  doujinshi: 'Doujinshi',
  manga: 'Manga',
  artist_cg: 'Artist CG',
  game_cg: 'Game CG',
  western: 'Western',
  non_h: 'Non-H',
  image_set: 'Image Set',
  cosplay: 'Cosplay',
  asian_porn: 'Asian Porn',
  misc: 'Misc',
}

/**
 * Category brand colors — chip backgrounds / grid corner triangles.
 * Exact values from roadmap §色彩系统 (Material palette).
 *
 * Supersedes the legacy numeric `CATEGORY_COLORS` in `./index.ts` (which uses a
 * different numbering and palette); component rendering must use this map.
 */
export const CATEGORY_COLOR_MAP: Readonly<Record<GalleryCategory, string>> = {
  doujinshi: '#f44336',
  manga: '#ff9800',
  artist_cg: '#fbc02d',
  game_cg: '#4caf50',
  western: '#8bc34a',
  non_h: '#2196f3',
  image_set: '#3f51b5',
  cosplay: '#9c27b0',
  asian_porn: '#9575cd',
  misc: '#f06292',
}

/**
 * Authoritative category bit values from Android `SiteConfig.java`.
 * Used BOTH as the numeric `GalleryInfo.category` value produced by the
 * parser AND as the search-filter exclusion bitmask bits.
 *
 * ⚠ The legacy `CATEGORY_MAP` in `./index.ts` uses a different (shifted)
 * numbering — do not rely on it; this table matches the Android source:
 * MISC=0x1 … WESTERN=0x200, UNKNOWN=0x400 (`SiteUtils.UNKNOWN`).
 */
export const CATEGORY_BIT_VALUES: Readonly<Record<GalleryCategory, number>> = {
  misc: 0x1,
  doujinshi: 0x2,
  manga: 0x4,
  artist_cg: 0x8,
  game_cg: 0x10,
  image_set: 0x20,
  cosplay: 0x40,
  asian_porn: 0x80,
  non_h: 0x100,
  western: 0x200,
}

/** Reverse lookup: numeric `GalleryInfo.category` bit → {@link GalleryCategory}. */
export const CATEGORY_BY_BIT: Readonly<Record<number, GalleryCategory | undefined>> = {
  0x1: 'misc',
  0x2: 'doujinshi',
  0x4: 'manga',
  0x8: 'artist_cg',
  0x10: 'game_cg',
  0x20: 'image_set',
  0x40: 'cosplay',
  0x80: 'asian_porn',
  0x100: 'non_h',
  0x200: 'western',
}

/* -------------------------------------------------------------------------- */
/* Atoms (F2)                                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Props for `RatingStars.vue` — replicates `SimpleRatingView.java`.
 *
 * Behavior: 5 stars in a row; star size 16dp (`R.dimen.rating_size`), gap 1dp
 * (`R.dimen.rating_interval`). Rating is on a 0–10 float scale; the display
 * quantum is computed as `clamp(Math.ceil(rating * 2), 0, 10)` giving
 * `floor(q / 2)` full stars, `q % 2` half stars, the rest outlines
 * (drawables `v_star_x16` / `v_star_half_x16` / `v_star_outline_x16`,
 * star color yellow 800 `#f9a825`).
 *
 * Purely presentational — no emits, no slots.
 */
export interface RatingStarsProps {
  /** Rating on the 0–10 scale (e.g. `gallery.rating`). Values outside are clamped. */
  rating: number
  /** Star edge size in px. @default 16 */
  size?: number
  /** Gap between stars in px. @default 1 */
  gap?: number
}

/**
 * Props for `CategoryChip.vue` — the colored category label tag shown on
 * list-mode gallery cards and the gallery detail header.
 * Background = {@link CATEGORY_COLOR_MAP}, label = {@link CATEGORY_LABELS}.
 */
export interface CategoryChipProps {
  /** Category to render; drives color and default label. */
  category: GalleryCategory
  /** Override the default label from {@link CATEGORY_LABELS}. */
  label?: string
  /** Whether the chip acts as a button (ripple + pointer). @default false */
  clickable?: boolean
}

/** Emits for `CategoryChip.vue`. */
export interface CategoryChipEmits {
  /** Chip tapped (only meaningful when `clickable`). */
  (e: 'click', category: GalleryCategory): void
}

/**
 * Props for `CategoryTriangle.vue` — the 32×24dp category-colored right-top
 * corner triangle on grid-mode tiles (roadmap §卡片规范).
 * Purely presentational — no emits, no slots.
 */
export interface CategoryTriangleProps {
  /** Category whose {@link CATEGORY_COLOR_MAP} color fills the triangle. */
  category: GalleryCategory
}

/**
 * Props for `AppCard.vue` — the app's restrained-Material card surface
 * (roadmap §卡片规范): radius 2dp, elevation/shadow 2dp, outer margin 2dp,
 * background = `contentColorPrimary` (theme-aware, see `AppTheme`).
 */
export interface AppCardProps {
  /** Card context: `list` (row card) or `grid` (tile). Affects sizing hints only. */
  mode: 'list' | 'grid'
}

/** Slots for `AppCard.vue`. */
export interface AppCardSlots {
  /** Card body content. */
  default(): any
}

/** Emits for `AppCard.vue`. */
export interface AppCardEmits {
  /** Card tapped (opens gallery detail in list screens). */
  (e: 'click', event: MouseEvent): void
}

/**
 * Props for `GalleryThumb.vue` — replicates `FixedThumb.java` / `TileThumb.java`:
 * an aspect-ratio-clamped thumbnail container
 * (`aspect-ratio` + `object-fit`, per roadmap mapping table).
 *
 * Android behavior:
 * - `TileThumb.setThumbSize(w, h)` clamps `w / h` into [0.33, 1.5], falling
 *   back to 0.67 when dimensions are unknown, and uses that as the container
 *   aspect ratio.
 * - `FixedThumb` uses CENTER_CROP (`object-fit: cover`) when the intrinsic
 *   aspect is inside (minAspect, maxAspect), otherwise FIT_CENTER
 *   (`object-fit: contain`).
 */
export interface GalleryThumbProps {
  /** Image URL (thumbnail endpoint or `/api/image/…?w=`). */
  src: string
  /** Known source width in px (gallery.thumbWidth); used to derive aspect. */
  thumbWidth?: number
  /** Known source height in px (gallery.thumbHeight); used to derive aspect. */
  thumbHeight?: number
  /**
   * Preset: `tile` applies TileThumb clamping (0.33–1.5, default 0.67);
   * `fixed` applies the explicit min/max below. @default 'tile'
   */
  variant?: 'fixed' | 'tile'
  /** Lower aspect bound for `fixed` variant. @default 0.33 */
  minAspect?: number
  /** Upper aspect bound for `fixed` variant. @default 1.5 */
  maxAspect?: number
  /** Accessible alt text. */
  alt?: string
  /** Defer loading until near viewport (IntersectionObserver). @default true */
  lazy?: boolean
}

/* -------------------------------------------------------------------------- */
/* Layout (F4 / F5)                                                           */
/* -------------------------------------------------------------------------- */

/**
 * One navigation drawer menu entry
 * (Android `nav_drawer_main.xml`: 8 items, single-checked group —
 * homepage / subscription / whats_hot / top_lists / favourite / history /
 * downloads / settings).
 */
export interface NavItem {
  /** Stable route/action id, e.g. `'homepage'`, `'downloads'`. */
  id: string
  /** Display label (i18n'd by the caller). */
  label: string
  /** Icon asset name — SVG converted from `drawable/v_*_black_x24.xml`. */
  icon: string
}

/**
 * Image quota shown by the drawer footer widget
 * (Android `LimitsCountView.kt` — "current / total" reset limits).
 */
export interface DrawerQuota {
  /** Limits consumed in the current reset period. */
  current: number
  /** Total limits for the reset period. */
  total: number
}

/**
 * Props for `NavigationDrawer.vue` — replicates the Android DrawerLayout
 * (roadmap §导航结构): max width 280dp; header 160dp with `sadpanda_low_poly`
 * background (user-swappable), 64dp circular avatar, 14sp white username;
 * 8-item single-select menu group; footer = quota widget + theme toggle.
 * Modal overlay on narrow viewports, persistent on wide ones (see
 * `contracts/responsive-strategy.md`).
 */
export interface NavigationDrawerProps {
  /** Whether the drawer is open. v-model:open. */
  open: boolean
  /** Menu entries; pass the canonical 8 (see {@link NavItem}). */
  items: NavItem[]
  /** `id` of the currently selected item, or null when none. */
  activeItemId?: string | null
  /** Logged-in user name shown in the header (14sp white). */
  username?: string
  /** Avatar image URL; rendered as a 64dp circle. */
  avatarUrl?: string
  /** Custom header background image URL (defaults to sadpanda low-poly). */
  headerBackgroundUrl?: string
  /** Quota for the footer `LimitsCountView` replica; null hides the widget. */
  quota?: DrawerQuota | null
  /** Current theme, so the footer toggle can reflect state. */
  theme?: AppTheme
}

/** Emits for `NavigationDrawer.vue`. */
export interface NavigationDrawerEmits {
  /** Drawer requested open/close (scrim tap, swipe). v-model:open. */
  (e: 'update:open', open: boolean): void
  /** A menu item was tapped; parent updates `activeItemId` and routes. */
  (e: 'select', item: NavItem): void
  /** Footer theme-toggle tapped; parent cycles {@link AppTheme}. */
  (e: 'toggle-theme'): void
  /** Footer quota refresh tapped (`LimitsCountView` refresh icon). */
  (e: 'refresh-quota'): void
}

/** Slots for `NavigationDrawer.vue`. */
export interface NavigationDrawerSlots {
  /** Replace the whole header (avatar + username area). */
  header?(): any
  /** Replace the whole footer (quota + theme toggle area). */
  footer?(): any
  /** Custom rendering for one menu row. */
  item?(props: { item: NavItem; active: boolean }): any
}

/**
 * The three view states of Android `ContentLayout`'s `ViewTransition`
 * (content list / center `ProgressView` / center tip with sadpanda drawable).
 */
export type ContentState = 'loading' | 'content' | 'empty'

/**
 * Props for `ContentLayout.vue` — replicates `ContentLayout.java`:
 * `ProgressView` + tip view + pull-to-refresh `RefreshLayout` (header AND
 * footer) + `EasyRecyclerView` + right-edge `FastScroller`.
 *
 * Android behavior notes for implementers:
 * - The tip (empty) view shows `big_sad_pandroid` above `emptyText` and
 *   RETRIGGERS a refresh on tap.
 * - Scrolling near the bottom auto-triggers footer refresh (infinite paging).
 * - FastScroller can be attached/detached at runtime (`showFastScroll` /
 *   `hideFastScroll`).
 */
export interface ContentLayoutProps {
  /** Which of the three internal views is shown. @default 'content' */
  state?: ContentState
  /** Empty-state message (Android `setEmptyString`). @default 'No hint' */
  emptyText?: string
  /** Header pull-refresh spinner active. v-model:refreshing. */
  refreshing?: boolean
  /** Footer "load next page" spinner active. */
  loadingMore?: boolean
  /** Enable pull-to-refresh header (Android `setRefreshLayoutEnable`). @default true */
  refreshEnabled?: boolean
  /** Show the right-edge FastScroller. @default true */
  fastScroll?: boolean
}

/** Emits for `ContentLayout.vue`. */
export interface ContentLayoutEmits {
  /** v-model:refreshing — header refresh started/finished. */
  (e: 'update:refreshing', refreshing: boolean): void
  /** Header pulled — reload first page. */
  (e: 'refresh'): void
  /** Scrolled near bottom — load next page (footer refresh). */
  (e: 'load-more'): void
  /** Empty-state tip tapped — retry (Android tip onClick → refresh()). */
  (e: 'retry'): void
}

/** Slots for `ContentLayout.vue`. */
export interface ContentLayoutSlots {
  /** The scrollable list content (rendered in the `content` state). */
  default(): any
  /** Custom empty state (replaces sadpanda + `emptyText`). */
  empty?(): any
}

/**
 * Props for `FastScroller.vue` — replicates `com.hippo.easyrecyclerview.FastScroller`:
 * a right-edge drag handle (30dp touch zone) with an accent-colored handler
 * drawable that tracks the scroll position and auto-hides when idle.
 * Usually composed inside `ContentLayout`; exposed separately for scenes that
 * attach it to their own scroll container (e.g. HistoryScene).
 */
export interface FastScrollerProps {
  /** Idle time in ms before the handle fades out. @default 1500 */
  autoHideDelay?: number
}

/** Slots for `FastScroller.vue`. */
export interface FastScrollerSlots {
  /** The scrollable content the scroller is attached to. */
  default(): any
}

/**
 * Props for `StaggeredGrid.vue` — web equivalent of
 * `AutoStaggeredGridLayoutManager`: column count derived from available width
 * (CSS `column-width` / container queries), NOT a fixed device-based count
 * (see `docs/webui-parallel-execution.md` §2.1).
 */
export interface StaggeredGridProps {
  /** Target column width in px; columns = floor(width / columnWidth). @default 120 */
  columnWidth?: number
  /** Gap between columns/rows in px. @default 4 */
  gap?: number
}

/** Slots for `StaggeredGrid.vue`. */
export interface StaggeredGridSlots {
  /** Grid items. */
  default(): any
}

/**
 * One secondary FAB in a `FabLayout` cluster
 * (Android: mini FloatingActionButton, 40dp — `R.dimen.fab_min_size`).
 */
export interface FabAction {
  /** Stable action id, e.g. `'refresh'`, `'random'`, `'select-all'`. */
  id: string
  /** Icon asset name (SVG from `drawable/v_*_dark_x24.xml`). */
  icon: string
  /** Tooltip / accessibility label. */
  label: string
  /** Per-action visibility (Android `setSecondaryFabVisibilityAt`). @default true */
  visible?: boolean
}

/**
 * Props for `FabLayout.vue` — replicates `FabLayout.java`: a bottom-right
 * cluster with ONE primary FAB (56dp, `R.dimen.fab_size`) and N secondary
 * mini FABs (40dp) stacked above it, expand/collapse animated (300ms,
 * fast-slow / slow-fast interpolators).
 *
 * Android defaults: `expanded = true`, `autoCancel = true` (tap on the layout
 * background collapses it), `hidePrimaryFab = false`.
 */
export interface FabLayoutProps {
  /** Icon for the primary 56dp FAB. */
  primaryIcon?: string
  /** Secondary 40dp FABs, rendered bottom-up above the primary. */
  actions: FabAction[]
  /** Whether the cluster is expanded. v-model:expanded. @default true */
  expanded?: boolean
  /** Tap outside the FABs collapses the cluster (Android `setAutoCancel`). @default true */
  autoCancel?: boolean
  /** Hide the primary FAB while collapsed (Android `setHidePrimaryFab`). @default false */
  hidePrimaryFab?: boolean
}

/** Emits for `FabLayout.vue`. */
export interface FabLayoutEmits {
  /** v-model:expanded — expand state changed. */
  (e: 'update:expanded', expanded: boolean): void
  /** Expand state changed (Android `OnExpandListener.onExpand`). */
  (e: 'expand', expanded: boolean): void
  /** Primary FAB tapped (Android `onClickPrimaryFab`). */
  (e: 'click-primary'): void
  /** Secondary FAB tapped (Android `onClickSecondaryFab` — with position). */
  (e: 'click-secondary', action: FabAction, index: number): void
}

/* -------------------------------------------------------------------------- */
/* Reader (F3 / F7)                                                           */
/* -------------------------------------------------------------------------- */

/**
 * Props for `ProgressSpinner.vue` — replicates `ProgressView.java`
 * (Material-style indeterminate ring: trim animations 1333ms, rotation 6665ms;
 * also supports determinate `progress`).
 * Sizes per roadmap mapping: Small 16dp / Large 76dp.
 */
export interface ProgressSpinnerProps {
  /** Size preset: `small` = 16px, `large` = 76px. */
  size: 'small' | 'large'
  /** Ring stroke color; defaults to theme accent (`widgetColorThemeAccent`). */
  color?: string
  /** Indeterminate spin vs determinate arc. @default true */
  indeterminate?: boolean
  /** Determinate progress in [0, 1]; used when `indeterminate` is false. @default 0 */
  progress?: number
}

/**
 * Props for `ReversibleSeekBar.vue` — replicates `ReversibleSeekBar.java`:
 * a standard seek bar whose drawing AND touch input are horizontally mirrored
 * when `reversed` is set (RTL reading direction).
 */
export interface ReversibleSeekBarProps {
  /** Current value, 0-based. v-model:value. */
  value: number
  /** Maximum value (inclusive). For pages: `totalPages - 1`. */
  max: number
  /** Mirror the bar (Android `setReverse`) for RTL reading. @default false */
  reversed?: boolean
  /** Disable interaction. @default false */
  disabled?: boolean
}

/** Emits for `ReversibleSeekBar.vue`. */
export interface ReversibleSeekBarEmits {
  /** v-model:value — live drag updates. */
  (e: 'update:value', value: number): void
  /** Drag committed (touch up) — page jump should apply. */
  (e: 'change', value: number): void
}

/**
 * Props for `SeekBarPanel.vue` — replicates the reader bottom panel from
 * `activity_gallery.xml` (`SeekBarPanel` + `ReversibleSeekBar` + two 32dp page
 * labels): horizontal bar, background `?gallerySliderBackgroundColor`
 * (#424242 dark / #212121 per roadmap), 48dp content height, 16dp horizontal
 * padding; left/right TextViews are 32dp wide, vertically centered.
 *
 * Page numbers are 1-based here ([1, totalPages]); the component maps to the
 * 0-based slider internally, exactly as GalleryActivity does.
 */
export interface SeekBarPanelProps {
  /** Current page, 1-based, in [1, totalPages]. v-model:currentPage. */
  currentPage: number
  /** Total page count of the gallery. */
  totalPages: number
  /** Reverse for RTL reading direction (Android `setReverse`). @default false */
  reversed?: boolean
}

/** Emits for `SeekBarPanel.vue`. */
export interface SeekBarPanelEmits {
  /** v-model:currentPage — live drag updates (1-based). */
  (e: 'update:currentPage', page: number): void
  /** Drag committed — jump to page (1-based). */
  (e: 'change', page: number): void
}

/* -------------------------------------------------------------------------- */
/* Search (F6)                                                                */
/* -------------------------------------------------------------------------- */

/**
 * `SearchBar` visual states — mirrors Android `SearchBar.STATE_*`:
 * - `normal`      — title row only (STATE_NORMAL = 0)
 * - `search`      — edit text focused, no suggestion list (STATE_SEARCH = 1)
 * - `search-list` — edit text + expanded suggestion list (STATE_SEARCH_LIST = 2)
 */
export type SearchBarState = 'normal' | 'search' | 'search-list'

/**
 * One suggestion row in the SearchBar dropdown
 * (Android `SearchBar.Suggestion`: primary line + optional secondary line,
 * e.g. tag keyword + translation; long-press deletes history entries).
 */
export interface SearchSuggestion {
  /** Primary line (the text inserted on tap). */
  text: string
  /** Optional secondary line (translation / hint). */
  hint?: string
}

/**
 * Props for `SearchBar.vue` — replicates `SearchBar.java` +
 * `widget_search_bar.xml`: a floating CardView
 * (margin 6dp h / 8dp v, `CardView.Normal`) with a 48dp row —
 * 48dp menu icon (12dp padding → 24dp glyph), title (`text_little_large` 20sp,
 * `textColorSecondary`, single line) swapped with the edit text
 * (`text_little_small` 16sp, `imeOptions=actionSearch`), 48dp action icon —
 * plus the clip-animated (300ms) suggestion list under a 1dp divider.
 */
export interface SearchBarProps {
  /** Visual state machine. v-model:state. @default 'normal' */
  state?: SearchBarState
  /** Title shown in `normal` state (Android `setTitle`). */
  title?: string
  /** Edit text content. v-model:query. */
  query?: string
  /** Edit text placeholder (Android `setEditTextHint`). */
  hint?: string
  /** Left (menu) icon asset; hidden when null (Android `setLeftDrawable(null)`). */
  leftIcon?: string | null
  /** Right (action) icon asset (Android `setRightDrawable`). */
  rightIcon?: string | null
  /** Allow submitting an empty query (Android `setAllowEmptySearch`). @default true */
  allowEmptySearch?: boolean
  /** Suggestion rows for the `search-list` state. */
  suggestions?: SearchSuggestion[]
}

/** Emits for `SearchBar.vue` — mirrors Android `SearchBar.Helper` + state listener. */
export interface SearchBarEmits {
  /** v-model:state — state machine transition (Android `OnStateChangeListener`). */
  (e: 'update:state', state: SearchBarState): void
  /** v-model:query — edit text changed. */
  (e: 'update:query', query: string): void
  /** Search applied — IME action or programmatic (Android `onApplySearch`). */
  (e: 'search', query: string): void
  /** Left/menu icon tapped (Android `onClickLeftIcon` — opens drawer). */
  (e: 'click-menu'): void
  /** Right/action icon tapped (Android `onClickRightIcon`). */
  (e: 'click-action'): void
  /** Title tapped while in `normal` state (Android `onClickTitle`). */
  (e: 'click-title'): void
  /** Suggestion row tapped (Android `Suggestion.onClick`). */
  (e: 'select-suggestion', suggestion: SearchSuggestion, index: number): void
  /** Suggestion row long-pressed — delete history entry (Android `onLongClick`). */
  (e: 'dismiss-suggestion', suggestion: SearchSuggestion, index: number): void
  /** Back pressed inside the edit text (Android `onSearchEditTextBackPressed`). */
  (e: 'back'): void
}

/** Top-level search mode — Android `SearchLayout.SEARCH_MODE_*`. */
export type SearchMode = 'normal' | 'image'

/**
 * Keyword search mode — Android `search_normal.xml` RadioGridGroup
 * (`R.id.search_normal_search` / `search_subscription_search` /
 * `search_specify_uploader` / `search_specify_tag`).
 */
export type NormalSearchMode = 'normal' | 'subscription' | 'uploader' | 'tag'

/**
 * Advanced-search bitmask bits — exact constants from
 * `AdvanceSearchTable.java` (SNAME … SFT).
 */
export const ADVANCE_SEARCH_BITS = {
  /** Search gallery name. */
  SNAME: 0x1,
  /** Search gallery tags. */
  STAGS: 0x2,
  /** Search gallery description. */
  SDESC: 0x4,
  /** Search torrent filenames. */
  STORR: 0x8,
  /** Only show galleries with torrents. */
  STO: 0x10,
  /** Search low-power tags. */
  SDT1: 0x20,
  /** Search downvoted tags. */
  SDT2: 0x40,
  /** Search expunged galleries. */
  SH: 0x80,
  /** Disable default language filter. */
  SFL: 0x100,
  /** Disable default uploader filter. */
  SFU: 0x200,
  /** Disable default tag filter. */
  SFT: 0x400,
} as const

/**
 * Advanced search options — mirrors `AdvanceSearchTable` state
 * (`getAdvanceSearch()` bitmask + `getMinRating()` + `getPageFrom/To()`),
 * field-compatible with `QuickSearch` in `./index.ts`.
 */
export interface AdvanceSearchOptions {
  /** Bitmask of {@link ADVANCE_SEARCH_BITS}. */
  advanceSearch: number
  /** Minimum rating filter, 2–5 (0 = disabled). */
  minRating: number
  /** Minimum page count (0 = unset). */
  pageFrom: number
  /** Maximum page count (0 = unset). */
  pageTo: number
}

/**
 * Props for `CategoryTable.vue` — replicates `CategoryTable.java`:
 * 10 `CheckTextView` blocks in 2 columns × 5 rows
 * (`category_table_item_height` 40dp, item margin 4dp), each colored by
 * {@link CATEGORY_COLOR_MAP}.
 *
 * ⚠ Android semantics are INVERTED: a CHECKED block means the category is
 * EXCLUDED (`getCategory()` sets the bit when NOT checked). This web contract
 * uses POSITIVE semantics instead — `selected` lists the categories INCLUDED
 * in the search. Implementers convert to the SiteConfig exclusion bitmask with
 * {@link CATEGORY_BIT_VALUES} (bit set = excluded) when building queries.
 *
 * Android long-press behavior (`onLongClick`): every OTHER block is set to
 * `!checked` of the pressed one — i.e. in positive semantics, long-pressing an
 * included category selects ONLY it.
 */
export interface CategoryTableProps {
  /** Categories INCLUDED (positive semantics — see note above). v-model:selected. */
  selected: GalleryCategory[]
}

/** Emits for `CategoryTable.vue`. */
export interface CategoryTableEmits {
  /** v-model:selected — block toggled. */
  (e: 'update:selected', selected: GalleryCategory[]): void
  /** Block long-pressed (Android `onLongClick` inversion rule applies). */
  (e: 'long-press', category: GalleryCategory): void
}

/* -------------------------------------------------------------------------- */
/* Gallery (S1 / S2 / S7)                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Props for `GalleryCard.vue` — the gallery list card in both modes
 * (roadmap §卡片规范, replicates `scene_gallery_list.xml` item layouts):
 *
 * - `list`: fixed 80×120dp (2:3) thumbnail left; right column = title (16sp,
 *   `textColorPrimary`, maxLines 2, end-ellipsize), uploader (14sp,
 *   `textColorSecondary`, single line), `RatingStars`, `CategoryChip`.
 * - `grid`: `GalleryThumb` tile (TileThumb aspect clamping) + 32×24dp
 *   `CategoryTriangle` at the top-right corner + language code badge
 *   (`gallery.simpleLanguage`, 10sp white bold).
 *
 * The card itself uses `AppCard` styling (2dp radius/shadow/margin,
 * theme-aware background). Derive the category via
 * `CATEGORY_BY_BIT[gallery.category]`.
 */
export interface GalleryCardProps {
  /** Gallery to render (numeric `category` is an {@link CATEGORY_BIT_VALUES} bit). */
  gallery: GalleryInfo
  /** Display mode, kept in sync with the list screen's layout mode. */
  mode: 'list' | 'grid'
}

/** Emits for `GalleryCard.vue`. */
export interface GalleryCardEmits {
  /** Card tapped — open gallery detail. */
  (e: 'click', gallery: GalleryInfo): void
}

/** Slots for `GalleryCard.vue`. */
export interface GalleryCardSlots {
  /** Optional overlay/badge area (e.g. download progress in S4 reuse). */
  overlay?(): any
}
