package com.hippo.ehviewer.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 6): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 6;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        GalleryTagsDao.createTable(db, ifNotExists);
        DownloadsDao.createTable(db, ifNotExists);
        DownloadLabelDao.createTable(db, ifNotExists);
        DownloadDirnameDao.createTable(db, ifNotExists);
        HistoryDao.createTable(db, ifNotExists);
        QuickSearchDao.createTable(db, ifNotExists);
        BlackListDao.createTable(db, ifNotExists);
        LocalFavoritesDao.createTable(db, ifNotExists);
        BookmarksBao.createTable(db, ifNotExists);
        FilterDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        GalleryTagsDao.dropTable(db, ifExists);
        DownloadsDao.dropTable(db, ifExists);
        DownloadLabelDao.dropTable(db, ifExists);
        DownloadDirnameDao.dropTable(db, ifExists);
        HistoryDao.dropTable(db, ifExists);
        QuickSearchDao.dropTable(db, ifExists);
        BlackListDao.dropTable(db, ifExists);
        LocalFavoritesDao.dropTable(db, ifExists);
        BookmarksBao.dropTable(db, ifExists);
        FilterDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(GalleryTagsDao.class);
        registerDaoClass(DownloadsDao.class);
        registerDaoClass(DownloadLabelDao.class);
        registerDaoClass(DownloadDirnameDao.class);
        registerDaoClass(HistoryDao.class);
        registerDaoClass(QuickSearchDao.class);
        registerDaoClass(BlackListDao.class);
        registerDaoClass(LocalFavoritesDao.class);
        registerDaoClass(BookmarksBao.class);
        registerDaoClass(FilterDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
