package com.hippo.ehviewer.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOWNLOAD_LABELS".
 */
@Entity(nameInDb = "DOWNLOAD_LABELS")
public class DownloadLabel {

    @Id
    private Long id;
    private String label;
    private long time;

    @Generated
    public DownloadLabel() {
    }

    public DownloadLabel(Long id) {
        this.id = id;
    }

    @Generated
    public DownloadLabel(Long id, String label, long time) {
        this.id = id;
        this.label = label;
        this.time = time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public long getTime() {
        return time;
    }

    public void setTime(long time) {
        this.time = time;
    }

}
