package com.hippo.ehviewer.dao;

import org.greenrobot.greendao.annotation.*;
import com.alibaba.fastjson.JSONObject;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Gallery_Tags".
 */
@Entity(nameInDb = "Gallery_Tags")
public class GalleryTags {

	@Id
	public long gid;
	public String rows;
	public String artist;
	public String cosplayer;
	public String character;
	public String female;
	public String group;
	public String language;
	public String male;
	public String misc;
	public String mixed;
	public String other;
	public String parody;
	public String reclass;
	public java.util.Date create_time;
	public java.util.Date update_time;

	@Generated
	public GalleryTags() {
	}

	public GalleryTags(long gid) {
		this.gid = gid;
	}

	@Generated
	public GalleryTags(long gid, String rows, String artist, String cosplayer, String character, String female,
			String group, String language, String male, String misc, String mixed, String other, String parody,
			String reclass, java.util.Date create_time, java.util.Date update_time) {
		this.gid = gid;
		this.rows = rows;
		this.artist = artist;
		this.cosplayer = cosplayer;
		this.character = character;
		this.female = female;
		this.group = group;
		this.language = language;
		this.male = male;
		this.misc = misc;
		this.mixed = mixed;
		this.other = other;
		this.parody = parody;
		this.reclass = reclass;
		this.create_time = create_time;
		this.update_time = update_time;
	}

	public long getGid() {
		return gid;
	}

	public void setGid(long gid) {
		this.gid = gid;
	}

	public String getRows() {
		return rows;
	}

	public void setRows(String rows) {
		this.rows = rows;
	}

	public String getArtist() {
		return artist;
	}

	public void setArtist(String artist) {
		this.artist = artist;
	}

	public String getCosplayer() {
		return cosplayer;
	}

	public void setCosplayer(String cosplayer) {
		this.cosplayer = cosplayer;
	}

	public String getCharacter() {
		return character;
	}

	public void setCharacter(String character) {
		this.character = character;
	}

	public String getFemale() {
		return female;
	}

	public void setFemale(String female) {
		this.female = female;
	}

	public String getGroup() {
		return group;
	}

	public void setGroup(String group) {
		this.group = group;
	}

	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getMale() {
		return male;
	}

	public void setMale(String male) {
		this.male = male;
	}

	public String getMisc() {
		return misc;
	}

	public void setMisc(String misc) {
		this.misc = misc;
	}

	public String getMixed() {
		return mixed;
	}

	public void setMixed(String mixed) {
		this.mixed = mixed;
	}

	public String getOther() {
		return other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public String getParody() {
		return parody;
	}

	public void setParody(String parody) {
		this.parody = parody;
	}

	public String getReclass() {
		return reclass;
	}

	public void setReclass(String reclass) {
		this.reclass = reclass;
	}

	public java.util.Date getCreate_time() {
		return create_time;
	}

	public void setCreate_time(java.util.Date create_time) {
		this.create_time = create_time;
	}

	public java.util.Date getUpdate_time() {
		return update_time;
	}

	public void setUpdate_time(java.util.Date update_time) {
		this.update_time = update_time;
	}

	@Override
	public String toString() {
		JSONObject jsonObject = (JSONObject) JSONObject.toJSON(this);
		return jsonObject.toJSONString();
	}

}
