package com.hippo.ehviewer.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "Black_List".
 */
@Entity(nameInDb = "Black_List")
public class BlackList {

	@Id(autoincrement = true)
	public Long id;

	@Index
	public String badgayname;
	public String reason;
	public String angrywith;
	public String add_time;
	public Integer mode;

	@Generated
	public BlackList() {
	}

	public BlackList(Long id) {
		this.id = id;
	}

	@Generated
	public BlackList(Long id, String badgayname, String reason, String angrywith, String add_time, Integer mode) {
		this.id = id;
		this.badgayname = badgayname;
		this.reason = reason;
		this.angrywith = angrywith;
		this.add_time = add_time;
		this.mode = mode;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getBadgayname() {
		return badgayname;
	}

	public void setBadgayname(String badgayname) {
		this.badgayname = badgayname;
	}

	public String getReason() {
		return reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getAngrywith() {
		return angrywith;
	}

	public void setAngrywith(String angrywith) {
		this.angrywith = angrywith;
	}

	public String getAdd_time() {
		return add_time;
	}

	public void setAdd_time(String add_time) {
		this.add_time = add_time;
	}

	public Integer getMode() {
		return mode;
	}

	public void setMode(Integer mode) {
		this.mode = mode;
	}

	@Override
	public String toString() {
		return badgayname;
	}

}
