package com.hippo.ehviewer.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "DOWNLOADED_FILES".
*/
public class DownloadedFilesDao extends AbstractDao<DownloadedFile, String> {

    public static final String TABLENAME = "DOWNLOADED_FILES";

    /**
     * Properties of entity DownloadedFile.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Token = new Property(0, String.class, "token", true, "TOKEN");
        public final static Property Gid = new Property(1, long.class, "gid", false, "GID");
        public final static Property Filename = new Property(2, String.class, "filename", false, "FILENAME");
        public final static Property Md5 = new Property(3, String.class, "md5", false, "MD5");
        public final static Property Path = new Property(4, String.class, "path", false, "PATH");
        public final static Property Size = new Property(5, Long.class, "size", false, "SIZE");
        public final static Property Download_time = new Property(6, long.class, "download_time", false, "DOWNLOAD_TIME");
        public final static Property Last_accessed = new Property(7, Long.class, "last_accessed", false, "LAST_ACCESSED");
        public final static Property Status = new Property(8, int.class, "status", false, "STATUS");
    };


    public DownloadedFilesDao(DaoConfig config) {
        super(config);
    }
    
    public DownloadedFilesDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"DOWNLOADED_FILES\" (" + //
                "\"TOKEN\" TEXT PRIMARY KEY NOT NULL ," + // 0: token
                "\"GID\" INTEGER NOT NULL ," + // 1: gid
                "\"FILENAME\" TEXT NOT NULL ," + // 2: filename
                "\"MD5\" TEXT," + // 3: md5
                "\"PATH\" TEXT NOT NULL ," + // 4: path
                "\"SIZE\" INTEGER," + // 5: size
                "\"DOWNLOAD_TIME\" INTEGER NOT NULL ," + // 6: download_time
                "\"LAST_ACCESSED\" INTEGER," + // 7: last_accessed
                "\"STATUS\" INTEGER NOT NULL );"); // 8: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"DOWNLOADED_FILES\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, DownloadedFile entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getToken());
        stmt.bindLong(2, entity.getGid());
        stmt.bindString(3, entity.getFilename());
 
        String md5 = entity.getMd5();
        if (md5 != null) {
            stmt.bindString(4, md5);
        }
        stmt.bindString(5, entity.getPath());
 
        Long size = entity.getSize();
        if (size != null) {
            stmt.bindLong(6, size);
        }
        stmt.bindLong(7, entity.getDownload_time());
 
        Long last_accessed = entity.getLast_accessed();
        if (last_accessed != null) {
            stmt.bindLong(8, last_accessed);
        }
        stmt.bindLong(9, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, DownloadedFile entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getToken());
        stmt.bindLong(2, entity.getGid());
        stmt.bindString(3, entity.getFilename());
 
        String md5 = entity.getMd5();
        if (md5 != null) {
            stmt.bindString(4, md5);
        }
        stmt.bindString(5, entity.getPath());
 
        Long size = entity.getSize();
        if (size != null) {
            stmt.bindLong(6, size);
        }
        stmt.bindLong(7, entity.getDownload_time());
 
        Long last_accessed = entity.getLast_accessed();
        if (last_accessed != null) {
            stmt.bindLong(8, last_accessed);
        }
        stmt.bindLong(9, entity.getStatus());
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    @Override
    public DownloadedFile readEntity(Cursor cursor, int offset) {
        DownloadedFile entity = new DownloadedFile( //
            cursor.getString(offset + 0), // token
            cursor.getLong(offset + 1), // gid
            cursor.getString(offset + 2), // filename
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // md5
            cursor.getString(offset + 4), // path
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // size
            cursor.getLong(offset + 6), // download_time
            cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7), // last_accessed
            cursor.getInt(offset + 8) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, DownloadedFile entity, int offset) {
        entity.setToken(cursor.getString(offset + 0));
        entity.setGid(cursor.getLong(offset + 1));
        entity.setFilename(cursor.getString(offset + 2));
        entity.setMd5(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPath(cursor.getString(offset + 4));
        entity.setSize(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setDownload_time(cursor.getLong(offset + 6));
        entity.setLast_accessed(cursor.isNull(offset + 7) ? null : cursor.getLong(offset + 7));
        entity.setStatus(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final String updateKeyAfterInsert(DownloadedFile entity, long rowId) {
        return entity.getToken();
    }
    
    @Override
    public String getKey(DownloadedFile entity) {
        if(entity != null) {
            return entity.getToken();
        } else {
            return null;
        }
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
