package com.hippo.ehviewer.dao;

import org.greenrobot.greendao.annotation.*;
import com.hippo.util.HashCodeUtils;
import com.hippo.yorozuya.ObjectUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "FILTER".
 */
@Entity(nameInDb = "FILTER")
public class Filter {

	@Id
	private Long id;
	public int mode;
	public String text;
	public Boolean enable;

	@Generated
	public Filter() {
	}

	public Filter(Long id) {
		this.id = id;
	}

	@Generated
	public Filter(Long id, int mode, String text, Boolean enable) {
		this.id = id;
		this.mode = mode;
		this.text = text;
		this.enable = enable;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getMode() {
		return mode;
	}

	public void setMode(int mode) {
		this.mode = mode;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public Boolean getEnable() {
		return enable;
	}

	public void setEnable(Boolean enable) {
		this.enable = enable;
	}

	@Override
	public int hashCode() {
		return HashCodeUtils.hashCode(mode, text);
	}

	@Override
	public boolean equals(Object o) {
		if (!(o instanceof Filter)) {
			return false;
		}
		Filter filter = (Filter) o;
		return filter.mode == mode && ObjectUtils.equal(filter.text, text);
	}

}
