/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hippo_lib_image_Image */

#ifndef _Included_com_hippo_lib_image_Image
#define _Included_com_hippo_lib_image_Image
#ifdef __cplusplus
extern "C" {
#endif
#undef com_hippo_lib_image_Image_FORMAT_UNKNOWN
#define com_hippo_lib_image_Image_FORMAT_UNKNOWN -1L
#undef com_hippo_lib_image_Image_FORMAT_PLAIN
#define com_hippo_lib_image_Image_FORMAT_PLAIN 0L
#undef com_hippo_lib_image_Image_FORMAT_JPEG
#define com_hippo_lib_image_Image_FORMAT_JPEG 1L
#undef com_hippo_lib_image_Image_FORMAT_PNG
#define com_hippo_lib_image_Image_FORMAT_PNG 2L
#undef com_hippo_lib_image_Image_FORMAT_GIF
#define com_hippo_lib_image_Image_FORMAT_GIF 3L
#undef com_hippo_lib_image_Image_FORMAT_WEBP
#define com_hippo_lib_image_Image_FORMAT_WEBP 4L
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeDecode
// * Signature: (Ljava/io/InputStream;Z)Lcom/hippo/lib/image/Image;
// */
//JNIEXPORT jobject JNICALL Java_com_hippo_lib_image_Image_nativeDecode
//  (JNIEnv *, jclass, jobject, jboolean);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeGetByteCount
// * Signature: (JI)I
// */
//JNIEXPORT jint JNICALL Java_com_hippo_lib_image_Image_nativeGetByteCount
//  (JNIEnv *, jclass, jlong, jint);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeComplete
// * Signature: (JI)Z
// */
//JNIEXPORT jboolean JNICALL Java_com_hippo_lib_image_Image_nativeComplete
//  (JNIEnv *, jclass, jlong, jint);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeIsCompleted
// * Signature: (JI)Z
// */
//JNIEXPORT jboolean JNICALL Java_com_hippo_lib_image_Image_nativeIsCompleted
//  (JNIEnv *, jclass, jlong, jint);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeTexImage
// * Signature: (JIZIIII)V
// */
//JNIEXPORT void JNICALL Java_com_hippo_lib_image_Image_nativeTexImage
//  (JNIEnv *, jclass, jlong, jint, jboolean, jint, jint, jint, jint);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeAdvance
// * Signature: (JI)V
// */
//JNIEXPORT void JNICALL Java_com_hippo_lib_image_Image_nativeAdvance
//  (JNIEnv *, jclass, jlong, jint);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeGetDelay
// * Signature: (JI)I
// */
//JNIEXPORT jint JNICALL Java_com_hippo_lib_image_Image_nativeGetDelay
//  (JNIEnv *, jclass, jlong, jint);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeFrameCount
// * Signature: (JI)I
// */
//JNIEXPORT jint JNICALL Java_com_hippo_lib_image_Image_nativeFrameCount
//  (JNIEnv *, jclass, jlong, jint);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeIsOpaque
// * Signature: (JI)Z
// */
//JNIEXPORT jboolean JNICALL Java_com_hippo_lib_image_Image_nativeIsOpaque
//  (JNIEnv *, jclass, jlong, jint);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeIsGray
// * Signature: (JII)Z
// */
//JNIEXPORT jboolean JNICALL Java_com_hippo_lib_image_Image_nativeIsGray
//  (JNIEnv *, jclass, jlong, jint, jint);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeClahe
// * Signature: (JIZ)V
// */
//JNIEXPORT void JNICALL Java_com_hippo_lib_image_Image_nativeClahe
//  (JNIEnv *, jclass, jlong, jint, jboolean);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeRecycle
// * Signature: (JI)V
// */
//JNIEXPORT void JNICALL Java_com_hippo_lib_image_Image_nativeRecycle
//  (JNIEnv *, jclass, jlong, jint);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeGetSupportedImageFormats
// * Signature: ()[I
// */
//JNIEXPORT jintArray JNICALL Java_com_hippo_lib_image_Image_nativeGetSupportedImageFormats
//  (JNIEnv *, jclass);
//
///*
// * Class:     com_hippo_lib_image_Image
// * Method:    nativeGetDecoderDescription
// * Signature: (I)Ljava/lang/String;
// */
//JNIEXPORT jstring JNICALL Java_com_hippo_lib_image_Image_nativeGetDecoderDescription
//  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
