package com.hippo.ehviewer.dao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DOWNLOADED_FILES".
 */
@Entity(nameInDb = "DOWNLOADED_FILES")
public class DownloadedFile {

    @Id
    @NotNull
    private String token;
    private long gid;

    @NotNull
    private String filename;
    private String md5;

    @NotNull
    private String path;
    private Long size;
    private long download_time;
    private Long last_accessed;
    private int status;

    @Generated
    public DownloadedFile() {
    }

    public DownloadedFile(String token) {
        this.token = token;
    }

    @Generated
    public DownloadedFile(String token, long gid, String filename, String md5, String path, Long size, long download_time, Long last_accessed, int status) {
        this.token = token;
        this.gid = gid;
        this.filename = filename;
        this.md5 = md5;
        this.path = path;
        this.size = size;
        this.download_time = download_time;
        this.last_accessed = last_accessed;
        this.status = status;
    }

    @NotNull
    public String getToken() {
        return token;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setToken(@NotNull String token) {
        this.token = token;
    }

    public long getGid() {
        return gid;
    }

    public void setGid(long gid) {
        this.gid = gid;
    }

    @NotNull
    public String getFilename() {
        return filename;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilename(@NotNull String filename) {
        this.filename = filename;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    @NotNull
    public String getPath() {
        return path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPath(@NotNull String path) {
        this.path = path;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    public long getDownload_time() {
        return download_time;
    }

    public void setDownload_time(long download_time) {
        this.download_time = download_time;
    }

    public Long getLast_accessed() {
        return last_accessed;
    }

    public void setLast_accessed(Long last_accessed) {
        this.last_accessed = last_accessed;
    }

    public int getStatus() {
        return status;
    }

    public void setStatus(int status) {
        this.status = status;
    }

}
